/*
 * MXL-JOURNAL-PERSISTENCE-001 — unified entry contract (frontend-only).
 *
 * This module has no I/O. It only defines the canonical entry shape
 * proposed in docs/architecture/MXL-JOURNAL-PERSISTENCE-001_ENTRY_CONTRACT.md
 * §4 and provides pure normalize/serialize/dedupe helpers around it. It does
 * not talk to a backend and does not assume one exists — `sync_status` is
 * always `local_only` until a real cloud contract is confirmed elsewhere.
 *
 * Field names and bounds here are a frontend proposal, not a backend fact
 * (see the entry-contract doc §3/§9 for the open backend questions this
 * does not answer). `entry_type` currently only carries `journal`, produced
 * by journalEntryAdapter.js from the existing journalStorage.js store —
 * other domains (check-in, one-shot practice completion) are intentionally
 * out of scope for this module; see docs/architecture/MXL-JOURNAL-PERSISTENCE-001_ENTRY_CONTRACT.md
 * for why they are tracked separately.
 */

const ENTRY_SCHEMA_VERSION = 1

const ENTRY_TYPES = ['journal']
const SOURCES = ['journal_flow']
const SYNC_STATUSES = ['local_only', 'synced', 'conflict']

const MAX_OUTCOME_LENGTH = 280
const MAX_REFLECTION_LENGTH = 4000
const MAX_NEXT_ACTION_LENGTH = 280

const ENTRY_KEY_ORDER = [
  'entry_id',
  'user_id',
  'entry_type',
  'started_at',
  'completed_at',
  'outcome',
  'reflection',
  'next_action',
  'source',
  'schema_version',
  'sync_status',
]

function boundedStringOrNull(value, maxLength) {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  if (!trimmed) return null
  return trimmed.length > maxLength ? trimmed.slice(0, maxLength) : trimmed
}

function isIsoTimestamp(value) {
  return typeof value === 'string' && value.includes('T') && !Number.isNaN(Date.parse(value))
}

/*
 * Deterministic 32-bit FNV-1a hash — not a cryptographic id. It exists only
 * to derive a stable entry_id from a natural key (schema + entry_type +
 * user + a caller-supplied stable key, e.g. calendar date) so the same
 * logical entry always resolves to the same id on every read, without
 * minting and persisting a random UUID at write time. Journal Flow already
 * upserts by calendar date (one entry per day), so date is that stable key
 * here. This is a frontend-only decision, open for backend review — see
 * entry-contract doc §9 ("entry ID — generated by client or server?").
 */
function fnv1a(input) {
  let hash = 0x811c9dc5
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return (hash >>> 0).toString(16).padStart(8, '0')
}

function deriveEntryId({ entryType, userId, naturalKey }) {
  return `j${ENTRY_SCHEMA_VERSION}_${fnv1a(`${ENTRY_SCHEMA_VERSION}:${entryType}:${userId}:${naturalKey}`)}`
}

/*
 * Validates and bounds an already-tagged entry object. Returns null for
 * anything unusable instead of throwing — malformed/legacy input (wrong
 * types, missing identity fields, garbage JSON round-tripped through
 * deserializeEntry) is dropped, never allowed to corrupt a list of entries.
 */
function normalizeEntry(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null

  const entryType = ENTRY_TYPES.includes(raw.entry_type) ? raw.entry_type : null
  const userId = typeof raw.user_id === 'string' && raw.user_id.trim() ? raw.user_id.trim() : null
  const entryId =
    typeof raw.entry_id === 'string' && raw.entry_id.trim() ? raw.entry_id.trim() : null
  if (!entryType || !userId || !entryId) return null

  return {
    entry_id: entryId,
    user_id: userId,
    entry_type: entryType,
    started_at: isIsoTimestamp(raw.started_at) ? raw.started_at : null,
    completed_at: isIsoTimestamp(raw.completed_at) ? raw.completed_at : null,
    outcome: boundedStringOrNull(raw.outcome, MAX_OUTCOME_LENGTH),
    reflection: boundedStringOrNull(raw.reflection, MAX_REFLECTION_LENGTH),
    next_action: boundedStringOrNull(raw.next_action, MAX_NEXT_ACTION_LENGTH),
    source: SOURCES.includes(raw.source) ? raw.source : null,
    schema_version: ENTRY_SCHEMA_VERSION,
    sync_status: SYNC_STATUSES.includes(raw.sync_status) ? raw.sync_status : 'local_only',
  }
}

/* Deterministic serialization: fixed key order, so the same logical entry
 * always produces byte-identical JSON regardless of construction order. */
function serializeEntry(entry) {
  const normalized = normalizeEntry(entry)
  if (!normalized) return null

  const ordered = {}
  for (const key of ENTRY_KEY_ORDER) ordered[key] = normalized[key]
  return JSON.stringify(ordered)
}

function deserializeEntry(json) {
  if (typeof json !== 'string') return null
  try {
    return normalizeEntry(JSON.parse(json))
  } catch {
    return null
  }
}

function recencyKey(entry) {
  return entry.completed_at || entry.started_at || ''
}

/* Duplicate protection: collapses entries sharing an entry_id, keeping the
 * most recently completed/started one. Safe against malformed input in the
 * input array — invalid entries are silently dropped, never thrown on. */
function dedupeEntries(entries) {
  if (!Array.isArray(entries)) return []

  const byId = new Map()
  for (const raw of entries) {
    const entry = normalizeEntry(raw)
    if (!entry) continue

    const existing = byId.get(entry.entry_id)
    if (!existing || recencyKey(entry).localeCompare(recencyKey(existing)) > 0) {
      byId.set(entry.entry_id, entry)
    }
  }
  return Array.from(byId.values())
}

export {
  ENTRY_KEY_ORDER,
  ENTRY_SCHEMA_VERSION,
  ENTRY_TYPES,
  MAX_NEXT_ACTION_LENGTH,
  MAX_OUTCOME_LENGTH,
  MAX_REFLECTION_LENGTH,
  SOURCES,
  SYNC_STATUSES,
  dedupeEntries,
  deriveEntryId,
  deserializeEntry,
  normalizeEntry,
  serializeEntry,
}
