import { defineConfig } from '@playwright/test'

export default defineConfig({
  testDir: './tests/ux',
  testMatch: [
    'ux-check.spec.mjs',
    'practices-rituals-ascezas.spec.mjs',
    'onboarding-age-gate.spec.mjs',
    'issue-648-independent-loading.spec.mjs',
    'checkin-geometry.spec.mjs',
    'evening-redo-from-card.spec.mjs',
    'profile-p11.spec.mjs',
    'profile-stoic.spec.mjs',
    'profile-wave2.spec.mjs',
    'profile-wave3.spec.mjs',
    'profile-canonical-streak.spec.mjs',
    'demo-phone.spec.mjs',
    'demo-panel.spec.mjs',
    'guest-save-reminder.spec.mjs',
    'bottom-nav-overlap.spec.mjs',
    'library-read-opens-catalog.spec.mjs',
    'library-read-opens-catalog.spec.mjs',
    'today-subscreen-navigation.spec.mjs',
  ],
  outputDir: 'artifacts/ux-check/playwright-output',
  fullyParallel: false,
  workers: 1,
  retries: 1,
  timeout: 90_000,
  expect: {
    timeout: 8_000,
  },
  reporter: 'line',
  use: {
    baseURL: 'http://127.0.0.1:4173',
    colorScheme: 'dark',
    reducedMotion: 'reduce',
    serviceWorkers: 'block',
    trace: 'off',
    video: 'off',
  },
  webServer: {
    command: 'npm run dev -- --host 127.0.0.1 --port 4173',
    url: 'http://127.0.0.1:4173',
    reuseExistingServer: false,
    timeout: 120_000,
  },
})
