import { platform } from '../platform'

export default function PracticeCard({
  title,
  subtitle,
  right,
  artwork,
  onOpen,
}) {
  return (
    <button
      type="button"
      onClick={() => {
        platform.haptic('light')
        onOpen?.()
      }}
      className="
        relative
        w-full
        h-[158px]
        rounded-[18px]
        bg-emerald
        overflow-hidden
        text-left
        border
        border-white/[0.16]
        active:scale-[0.985]
        transition-transform
        flex
        flex-col
      "
    >
      {right && (
        <span
          className="
            absolute
            top-[8px]
            right-[8px]
            z-10
            h-[26px]
            min-w-[40px]
            px-[8px]
            rounded-full
            flex
            items-center
            justify-center
            font-mono
            text-[11px]
            font-medium
            leading-none
            text-gold
            bg-gold/[0.025]
            border
            border-gold/[0.42]
          "
        >
          {right}
        </span>
      )}

      <div
        className="
          w-full
          h-[88px]
          px-[6px]
          pt-[4px]
          flex
          items-center
          justify-center
          shrink-0
        "
      >
        <div
          className="
            w-full
            h-full
            flex
            items-center
            justify-center
            scale-[1.08]
          "
        >
          {artwork}
        </div>
      </div>

      <div
        className="
          flex-1
          w-full
          px-[12px]
          pb-[10px]
          flex
          flex-col
          justify-end
        "
      >
        <div
          className="
            font-display
            text-[15px]
            font-bold
            text-cream
            leading-[1.05]
            tracking-[-0.025em]
          "
        >
          {title}
        </div>

        <div
          className="
            text-[11px]
            text-cream/[0.48]
            font-normal
            mt-[4px]
            leading-[1.2]
            tracking-[-0.01em]
          "
        >
          {subtitle}
        </div>
      </div>
    </button>
  )
}